#------------------------------------------------------------------------------
# Makefile for IntegerStackTest.c
#------------------------------------------------------------------------------

ASSIGNMENT     = lab3
CLIENT         = IntegerStackTest
ADT            = IntegerStack
SOURCE         = $(CLIENT).c
OBJECT         = $(CLIENT).o
ADT_SOURCE     = $(ADT).c
ADT_OBJECT     = $(ADT).o
ADT_HEADER     = $(ADT).h
COMPILE        = gcc -c -std=c99 -Wall
LINK           = gcc -o
REMOVE         = rm -f
MEMCHECK       = valgrind --leak-check=full
FILES          = README IntegerStack.c IntegerStackTest.c IntegerStack.h Makefile
SUBMIT	       = submit cse015-pt.f19 $(ASSIGNMENT)

$(CLIENT) : $(OBJECT) $(ADT_OBJECT) 
	$(LINK) $(CLIENT) $(OBJECT) $(ADT_OBJECT) 

$(OBJECT) : $(SOURCE) $(ADT_HEADER) 
	$(COMPILE) $(SOURCE)

$(ADT_OBJECT) : $(ADT_SOURCE) $(ADT_HEADER)
	$(COMPILE) $(ADT_SOURCE)

clean :
	$(REMOVE) $(CLIENT) $(OBJECT) $(ADT_OBJECT) 

memcheck : $(CLIENT)
	$(MEMCHECK) $(CLIENT)

submit :
	$(SUBMIT) $(FILES)
